extends: stylelint-config-standard
rules:
  declaration-empty-line-before:
    - never
    - ignore:
      - after-declaration

  at-rule-no-vendor-prefix: null
  no-descending-specificity: null
  no-duplicate-selectors: null
  rule-empty-line-before: null
  selector-class-pattern: null
  selector-id-pattern: null
